server:
  port: 80
  servlet:
    path: /
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssm
    username: root
    password: root
  thymeleaf:
    cache: false
mybatis:
  type-aliases-package: com.itheima.domain
  configuration:
    map-underscore-to-camel-case: true
# mapper-locations: com/itheima/dao/*.xml
